---
- name: Install Python and Required Libraries in Containers
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python and dependencies
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
        state: present

    - name: Create a Python virtual environment
      command: python3 -m venv /opt/venv
      args:
        creates: /opt/venv

    - name: Install Python 'requests' Library in virtual environment
      pip:
        name: requests
        virtualenv: /opt/venv

- name: Deploy Nginx
  hosts: nginx
  gather_facts: false
  roles:
    - nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- name: Deploy PostgreSQL
  hosts: postgres
  gather_facts: false
  roles:
    - postgresql

- name: Install vim
  hosts: nginx
  tasks:
    - name: Ensure vim is installed
      package:
        name: vim
        state: latest
