---
- name: Install Python and Required Libraries in Containers
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python (Debian/Ubuntu)
      raw: apt-get update && apt-get install -y python3 python3-venv python3-pip

    - name: Create a Python virtual environment
      raw: python3 -m venv /opt/venv

    - name: Install Python 'requests' Library in virtual environment
      raw: /opt/venv/bin/pip install requests

- name: Deploy Nginx
  hosts: nginx
  gather_facts: false
  roles:
    - nginx

- name: Deploy PostgreSQL
  hosts: postgres
  gather_facts: false
  roles:
    - postgresql

- name: Install vim
  hosts: nginx
  tasks:
    - name: Ensure vim is installed
      package:
        name: vim
        state: latest
